const pets = [
  {
    id: "1",
    type: "Dog",
    name: "Bradley",
    adoptionStatus: "Adopted",
    picture: "",
    height: 14,
    weight: 75,
    color: "White/Blue",
    bio: "",
    hypoallergnic: false,
    dietery: [],
    breed: "Pit Bull Mix",
  },
  {
    id: "2",
    type: "Cat",
    name: "Rajah",
    adoptionStatus: "Adopted",
    picture: "",
    height: 4,
    weight: 65,
    color: "Brown Tabby",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    id: "3",
    type: "Cat",
    name: "Pebbles",
    adoptionStatus: "Adopted",
    picture: "",
    height: 84,
    weight: 75,
    color: "Calico",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    id: "4",
    type: "Dog",
    name: "Johnny",
    adoptionStatus: "Adopted",
    picture: "",
    height: 66,
    weight: 88,
    color: "Blue/White",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Pit Bull",
  },
  {
    id: "5",
    type: "Cat",
    name: "Miso",
    adoptionStatus: "Adopted",
    picture: "",
    height: 26,
    weight: 8,
    color: "Brown Tabby/White",
    bio: "",
    hypoallergnic: false,
    dietery: [],
    breed: "Domestic Shorthair Mix",
  },
  {
    id: "6",
    type: "Cat",
    name: "Lucky Charm",
    adoptionStatus: "Adopted",
    picture: "",
    height: 10,
    weight: 69,
    color: "Orange Tabby",
    bio: "",
    hypoallergnic: true,
    dietery: [],
    breed: "Domestic Shorthair Mix",
  },
];

export default pets;
